FROM node:22-alpine as builder
WORKDIR /my-space

COPY package.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn build

FROM node:22-alpine as runner
WORKDIR /my-space
COPY --from=builder /my-space/package.json .
COPY --from=builder /my-space/yarn.lock .
COPY --from=builder /my-space/next.config.mjs ./
COPY --from=builder /my-space/public ./public
COPY --from=builder /my-space/.next/standalone ./
COPY --from=builder /my-space/.next/static ./.next/static
EXPOSE 3000

ENTRYPOINT ["node", "./server.js"]