services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    env_file: .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 2s
      timeout: 1s
      retries: 20

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: ./frontend/.env.local
    volumes:
      - ./frontend:/app
