# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    env_file: .env
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
